# Generated by Django 4.0.1 on 2022-01-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('SALARY', 'SALARY'), ('SIDE_HUSTLE', 'SIDE_HUSTLE'), ('COMMISIONS', 'COMMISIONS'), ('OTHE', 'OTHE')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
